Milestone3
shloch/REACT_CALCULATOR pull request #3
Opened 2019-10-18 18:42 UTC by shloch

for code review
- Designed the UI of the calculator app ( ``` src/index.css ``` )
Enabling FLEX displays, some default prop values necessary too alter designs

2019-10-18 20:29 UTC, BalintMendli requested changes
Hi @shloch ,

The calculator looks great. 👏 

We just need to make some changes regarding Button's props.

Please check my comments and update the app.

**When done please submit another review request.**

_As always if you have any questions let me know on Slack._

2019-10-18 20:29 UTC, zenott commented on src/components/Button.js
> +    }
Let's set defaultProps for the color prop and then we don't need this logic.
Also set color's propType.

2019-10-18 20:29 UTC, zenott commented on src/components/Button.js
> +      <button className={`${wideStyle}`} id='button-component' style={bgColor}>
The template literal is unnecessary here. Could be just `className={wideStyle}`.

2019-10-18 20:29 UTC, zenott commented on src/components/ButtonPanel.js
> +          <Button name='AC' color='' wide='' />
Let's set the colors for buttons that does not have the default orange color.

2019-10-20 14:44 UTC, shloch commented
@zenott thanks for the reviews, learning a lot from them :)

2019-10-21 08:12 UTC, SunnyAsar requested changes
# Hello @shloch 👋 
This is looking Good now, please just fix the linting error, lets just have stickler green.

**request another review when it's done**

2019-10-21 08:14 UTC, SunnyAsar approved these changes
# Hi @shloch 👍 
You had it fixed before i finished my review.
Good Work.

# You May pass 👍

2019-10-21 10:22 UTC, merged